### ISSUE TITLE
keyboard.currentLayout didn't work on wayland.

### ISSUE THREAD

**Issue by ffs-akl** [birbkeks/win10-sddm-theme#7]
I guess that the layout.qml component didn't get the information of keyboard on wayland.
I tried to edit the text in layout.qml, the text edited was displaied there.    and tried to run sddm on X11, the keyboard.currentLayout  worked fine.

**Comment by syrupderg** [comment]
can you provide screenshots/pictures?

**Comment by ffs-akl** [comment]
Please see the following photo
1. Mouse hover on keyboard.currentLayout botton  (Wayland)
  
<img width="694" height="342" alt="Image" src="https://github.com/user-attachments/assets/4eb5f5c3-41ca-4db0-9241-48f3b32c6dc4" />

2. Clilked on keyboard.currentLayout (Wayland)
  

<img width="642" height="263" alt="Image" src="https://github.com/user-attachments/assets/eabed2a5-3942-4bea-a436-17ccca0900fe" />

3. keyboard.currentLayout worked fine (X11)

<img width="468" height="276" alt="Image" src="https://github.com/user-attachments/assets/c1510ee2-1116-43ca-8ecd-cf1f5646e6c4" />

**Comment by syrupderg** [comment]
fixed, wait for the new release. 
(this issue isnt caused by this theme but rather because of the new releases of qt or sddm because ```keyboard.layouts[keyboard.currentLayout].shortName``` works on xorg but not on wayland while ```keyboard.layouts[keyboard.currentLayout].longName``` works on both. 
to fix it i just implemented my own list of short code version of country names so not all countries might be listed)

**Comment by ffs-akl** [comment]
"I think this issue is related to the data synchronization between the Wayland compositor and SDDM, similar to the discussion here: https://github.com/labwc/labwc/discussions/3354.

Even with the latest git version and the syntax errors fixed (like the missing comma ), the layout still doesn't show up because keyboard.layouts might be empty under Wayland."

<img width="723" height="694" alt="Image" src="https://github.com/user-attachments/assets/a5d82afd-8ae5-4f3b-a97c-1e2ee2476792" />

<img width="484" height="432" alt="Image" src="https://github.com/user-attachments/assets/ed9bec46-415d-4411-bf66-1cab5920fdaf" />

**Comment by syrupderg** [comment]
dang it

**Comment by ffs-akl** [comment]
I believe this is a core SDDM bug rather than a theme issue. Even the fallback theme ('maui') exhibits the same behavior.
